apiVersion: v1
kind: Pod
metadata:
  name: app-env-test
spec:
  containers:
  - name: app
    image: busybox
    command: ["sleep", "3600"]
    envFrom:
    - configMapRef:
        name: app-config
    - secretRef:
        name: app-secret
