from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor, white
from reportlab.pdfbase.pdfmetrics import stringWidth
import os

W = H = 1080
OUT = "/mnt/user-data/outputs"

GUIDES = {
    "k3s":     dict(p=HexColor("#0A66C2"), d=HexColor("#064A91"), m=HexColor("#3A8FD4"), l=HexColor("#D6E9FA"), name="K3s", version="v1.35.3"),
    "docker":  dict(p=HexColor("#1D63ED"), d=HexColor("#0E3FA8"), m=HexColor("#4A7FEE"), l=HexColor("#D6E6FF"), name="Docker", version="Engine v29"),
    "helm":    dict(p=HexColor("#4F1DB5"), d=HexColor("#31138A"), m=HexColor("#7B52D4"), l=HexColor("#EAE4FB"), name="Helm", version="v4.1.3"),
    "k8s":     dict(p=HexColor("#326CE5"), d=HexColor("#1A4DB8"), m=HexColor("#5C8FEF"), l=HexColor("#D6E6FF"), name="Kubernetes", version="v1.35"),
    "compose": dict(p=HexColor("#0A5EB8"), d=HexColor("#064A91"), m=HexColor("#3A8FD4"), l=HexColor("#D6E9FA"), name="Docker Compose", version="v2"),
    "actions": dict(p=HexColor("#1F883D"), d=HexColor("#116329"), m=HexColor("#3DAB5C"), l=HexColor("#D4F5DC"), name="GitHub Actions", version="2026"),
    "argocd":  dict(p=HexColor("#EF7B4D"), d=HexColor("#B85C30"), m=HexColor("#F4A27A"), l=HexColor("#FDE8DC"), name="ArgoCD", version="v3.3.6"),
    "prom":    dict(p=HexColor("#E6522C"), d=HexColor("#A83510"), m=HexColor("#F08060"), l=HexColor("#FDE8DC"), name="Prometheus", version="v3.11.1"),
    "grafana": dict(p=HexColor("#F46800"), d=HexColor("#B34D00"), m=HexColor("#F88C3A"), l=HexColor("#FEF0E0"), name="Grafana", version="v11.x"),
    "loki":    dict(p=HexColor("#6B4FBB"), d=HexColor("#4A3488"), m=HexColor("#9B7FDB"), l=HexColor("#EDE8FA"), name="Loki + OTel", version="v3.6"),
}

INK  = HexColor("#0D1B2A")
GRAY = HexColor("#6B7280")
LGRAY= HexColor("#F1F5F9")
WHITE= white
GREEN= HexColor("#166534")
GREEN_L = HexColor("#DCFCE7")

QA_DATA = {
"k3s": [
    ("Installation",        [("What is the node status after installation and what role is assigned?",       "Ready — control-plane,master", "kubeadm labels the first node as both control-plane and master. Check with kubectl get nodes."),("Which processes does K3s start?",          "k3s server (or k3s agent)", "ps aux | grep k3s shows the main process plus child processes like containerd, flannel, etc."),("Which container runtime is used by default?","containerd",  "K3s uses containerd as default CRI since v1.23. Verify: k3s crictl info."),("Where is the cluster database stored?",   "/var/lib/rancher/k3s/server/db/", "SQLite by default. Switch to etcd with --cluster-init for HA.")]),
    ("Multi-Node Cluster",  [("What interface does Flannel create?",      "flannel.1 (VXLAN interface)", "Flannel creates flannel.1 on each node. Run: ip link show flannel.1."),("What is the default pod CIDR?",           "10.42.0.0/16",    "K3s default pod CIDR. Change at install with --cluster-cidr."),("How do you pin a pod to a specific node?","nodeSelector in pod spec", "Add nodeSelector: kubernetes.io/hostname: <node-name> or use nodeName field.")]),
    ("Deployments",         [("How many ReplicaSets after update and why?","2 ReplicaSets",    "Kubernetes keeps the old RS (scaled to 0) for rollback capability. helm rollout undo uses it."),("Difference: ClusterIP vs NodePort vs LoadBalancer?", "ClusterIP=internal only, NodePort=host port, LoadBalancer=cloud LB", "ClusterIP is cluster-internal. NodePort opens a port on every node. LoadBalancer provisions a cloud load balancer."),("Scale to 5 replicas in one command?",     "kubectl scale deploy <n> --replicas=5", "The quickest way. Or edit the manifest and re-apply.")]),
    ("Ingress with Traefik",[("Ingress vs LoadBalancer?",                  "Ingress routes HTTP/S by host+path; LoadBalancer gets a cloud IP", "Ingress is layer 7 (HTTP). LoadBalancer is layer 4 (TCP). Ingress is far more efficient for HTTP workloads."),("Enable HTTPS with self-signed cert?",    "Use Traefik TLSOption or cert-manager", "Add TLS block to Ingress + a TLS Secret. For auto HTTPS use cert-manager with a ClusterIssuer."),("Two Ingresses with same host?",          "Last one applied wins (or undefined conflict)", "Ingress controllers handle host conflicts differently. Traefik merges path rules; conflicts cause unpredictable routing.")]),
    ("Persistent Storage",  [("Where is PV data stored on the node?",     "/var/lib/rancher/k3s/storage/<pvc-name>/", "local-path-provisioner creates a directory per PVC. Check: kubectl describe pv <name>."),("PV node goes down — what happens?",     "Pod stays Pending until that node returns", "local-path PVs are node-local. Without the node, the PVC cannot be mounted anywhere else."),("Shared storage across nodes?",          "Longhorn, NFS, or a cloud storage class", "Longhorn replicated volumes or NFS PVs support ReadWriteMany for multi-node access.")]),
    ("ConfigMaps & Secrets",[("Difference: ConfigMap vs Secret in etcd?", "Secrets are base64-encoded; both stored in etcd", "Secrets are base64 (not encrypted) by default. Enable EncryptionConfiguration for real encryption at rest."),("Mount ConfigMap as a volume?",          "Use volumes.configMap + volumeMounts in pod spec", "Each key in the ConfigMap becomes a file. Great for config files like nginx.conf or app.yaml."),("2 more secure alternatives to native Secrets?","Sealed Secrets, External Secrets Operator", "Sealed Secrets encrypts with a cluster key. ESO syncs from Vault, AWS Secrets Manager, etc.")]),
    ("Monitoring & Debug",  [("Different pod phases?",                    "Pending, Running, Succeeded, Failed, Unknown", "Pending = waiting for scheduling/images. Running = at least one container running. Unknown = node lost."),("CrashLoopBackOff vs ImagePullBackOff?", "Crash=container starts then dies; ImagePull=can't pull the image", "CrashLoopBackOff: container starts but exits with error. ImagePullBackOff: Docker registry unreachable or image not found."),("Stream logs from multiple pods?",        "kubectl logs -l app=myapp --all-containers -f", "The -l flag selects by label. --all-containers includes init containers.")]),
    ("HA & Production",     [("Minimum nodes for etcd quorum?",           "3 nodes (odd number required)", "etcd uses Raft consensus. With 3 nodes it tolerates 1 failure. With 5 it tolerates 2. Even numbers give no benefit."),("Guaranteed vs Burstable vs BestEffort?", "Guaranteed=requests=limits, Burstable=partial, BestEffort=none", "Guaranteed pods are never OOM-killed first. BestEffort are killed first under memory pressure."),("Tools for K3s monitoring?",             "Prometheus + Grafana, Lens IDE, k9s", "kube-prometheus-stack Helm chart gives full monitoring in one command. k9s and Lens for interactive cluster management.")]),
],
"docker": [
    ("Installation & Setup",[("Default storage driver on v29 fresh install?","overlayfs (containerd image store)", "Docker Engine v29 switched to containerd image store as default. Run: docker info | grep -i storage."),("docker-ce vs docker-ce-cli?",           "docker-ce=daemon, docker-ce-cli=client", "docker-ce is the background daemon (dockerd). docker-ce-cli is the 'docker' command you type. They communicate via the socket."),("Why add user to docker group?",         "To run docker without sudo", "The docker socket is owned by root. Group membership grants socket access. Security risk: docker group = effective root."),("What happens when you run hello-world?", "Pull image → create container → run → print → exit", "Docker checks local cache, pulls from Hub if missing, creates a container from the image, runs it, output is printed, container exits.")]),
    ("Images",              [("What is an image layer?",                  "A read-only filesystem diff stored as a tar", "Each RUN/COPY/ADD in Dockerfile creates a new layer. Layers are shared across images, saving disk space."),("What is the build cache?",              "Cached intermediate layers reused if inputs unchanged", "Cache is invalidated when a layer's instruction or input files change. COPY . . invalidates everything below it."),("CMD vs ENTRYPOINT?",                   "ENTRYPOINT=fixed executable, CMD=default args", "ENTRYPOINT sets the command that always runs. CMD provides default arguments that can be overridden at runtime.")]),
    ("Containers",          [("docker stop vs docker kill?",              "stop=SIGTERM then SIGKILL, kill=immediate SIGKILL", "docker stop sends SIGTERM, waits 10s, then SIGKILL. docker kill sends SIGKILL immediately — no graceful shutdown."),("What does --rm do?",                   "Automatically removes container when it exits", "Useful for one-off commands. Without --rm, stopped containers accumulate and consume disk space."),("Copy file from container to host?",     "docker cp <container>:/path/file ./local/", "Works on running and stopped containers. Reverse direction: docker cp ./local/ <container>:/path/")]),
    ("Networking",          [("Why can containers on custom network use DNS?","Docker's embedded DNS resolver maps container names", "User-defined bridges get a DNS server at 127.0.0.11. The default bridge network does NOT have this feature."),("-p 80:80 vs -p 127.0.0.1:80:80?",      "First=all interfaces, Second=localhost only", "127.0.0.1:80:80 binds only to localhost — not accessible from outside the host. Useful for security."),("Connect running container to network?",  "docker network connect <network> <container>", "A container can be on multiple networks simultaneously. Disconnect with docker network disconnect.")]),
    ("Volumes",             [("Named volume vs bind mount?",              "Named=Docker-managed path, Bind=any host path", "Named volumes are portable and work anywhere. Bind mounts depend on the host directory existing."),("Where are named volumes stored?",       "/var/lib/docker/volumes/<name>/_data/", "Find exact path: docker volume inspect <name> | grep Mountpoint."),("How to backup a Docker volume?",        "docker run --rm -v vol:/data -v $(pwd):/bak alpine tar czf /bak/vol.tar.gz /data", "Spin up a temporary alpine container that can access the volume and create a tar archive.")]),
    ("Dockerfile",          [("How does multi-stage reduce image size?",  "Only final stage artifacts are in the output image", "Builder stage compiles/installs everything. Final stage COPYs only the runtime artifacts. Dev tools stay out of production."),("Why not run as root in production?",   "Security: container breakout = root on host", "A process running as root inside a container that escapes gets root on the host. Always use USER directive."),("What does .dockerignore do?",           "Excludes files from the build context sent to daemon", "Without it, node_modules, .git, and secrets are sent to the daemon unnecessarily, slowing builds and leaking data.")]),
    ("Docker Compose",      [("docker compose stop vs down?",            "stop=containers stopped, down=containers removed", "stop preserves containers and volumes. down removes containers and networks. down -v also removes volumes."),("Scale a service to 3 replicas?",        "docker compose up --scale api=3", "Or set replicas: 3 under deploy: in compose.yaml. Scaled services cannot have fixed port mappings."),("Override values for different envs?",   "Use -f compose.override.yaml or multiple -f flags", "docker compose -f compose.yaml -f compose.prod.yaml up -d. Values in later files override earlier ones.")]),
    ("Production & Security",[("Container exceeds memory limit?",         "OOM-killed by the kernel, container restarts", "The kernel sends SIGKILL. Docker reports OOMKilled: true in inspect. Set --memory-swap equal to --memory to prevent swap."),("--cap-drop and least privilege?",       "Drops Linux capabilities the process doesn't need", "Containers inherit ~14 capabilities by default. --cap-drop=ALL removes them all. Add back only what's needed (e.g. NET_BIND_SERVICE)."),("Configure default private registry?",   "Set 'registry-mirrors' or 'insecure-registries' in /etc/docker/daemon.json", "Add: {\"registry-mirrors\": [\"https://my-registry.example.com\"]} to daemon.json and restart dockerd.")]),
],
"helm": [
    ("First Chart",         [("Difference: chart vs release?",           "Chart=package definition, Release=running instance", "A chart is like a Docker image. A release is like a container — one chart can have many releases with different values."),("Where does Helm store release state?",  "As Kubernetes Secrets in the target namespace", "Each revision gets one Secret named sh.helm.release.v1.<name>.v<N>. Run: kubectl get secrets | grep helm."),("What happens on helm uninstall?",       "All chart resources are deleted from the cluster", "Kubernetes objects (Deployment, Service, etc.) are removed. Use --keep-history to retain release history for rollback."),("List releases in all namespaces?",      "helm list -A",  "The -A flag means all namespaces. Without it, Helm only shows releases in the current namespace.")]),
    ("Chart Structure",     [("version vs appVersion in Chart.yaml?",    "version=chart package version, appVersion=app being packaged", "Bump 'version' when templates change. Bump 'appVersion' when the application itself changes. They are independent."),("What is a library chart?",             "A chart with reusable templates, not deployable alone", "Library charts export named templates via define. They cannot be installed directly — only used as dependencies."),("What does 'condition' in dependency do?","Enables or disables the dependency based on a values flag", "condition: postgresql.enabled means the PostgreSQL dependency is only included if .Values.postgresql.enabled is true.")]),
    ("Templating",          [("What does '-' in {{- and -}} do?",        "Trims whitespace (newlines/spaces) on that side", "{{- trims leading whitespace. -}} trims trailing. Critical for clean YAML output — extra spaces can break K8s manifests."),(".Values vs .Release vs .Chart?",        ".Values=user config, .Release=release metadata, .Chart=chart metadata", ".Release.Name is the helm install name. .Chart.Name is from Chart.yaml. .Values is from values.yaml + --set overrides."),("Default value in template?",           "{{ .Values.port | default 8080 }}", "The 'default' function returns the fallback when the value is nil or empty. Use 'required' to fail if a value is missing.")]),
    ("Repositories",        [("What does helm repo update do?",          "Fetches latest chart index from all configured repos", "Repos publish an index.yaml. helm repo update downloads fresh copies. Without it you may install stale chart versions."),("Search Artifact Hub from CLI?",        "helm search hub <term>",  "helm search hub searches artifacthub.io. helm search repo searches only your locally configured repos."),("helm search repo vs helm search hub?", "repo=local repos only, hub=public artifacthub.io", "hub has 15,000+ charts. repo is faster and searches only repos you've explicitly added with helm repo add.")]),
    ("Releases",            [("What does --atomic do on upgrade?",        "Auto-rollback to previous revision if upgrade fails", "If any resource fails to deploy, Helm rolls back automatically. Combine with --timeout to set max wait time."),("How many revisions kept by default?",  "10 revisions",  "Change with --history-max flag or historyMax in values. Each revision is one Kubernetes Secret."),("helm rollback vs re-running upgrade?", "rollback restores previous manifest; upgrade applies new one", "rollback is instant — it reapplies the stored previous manifest. upgrade runs the full template + apply cycle.")]),
    ("Hooks & Tests",       [("What if a pre-install hook fails?",        "The install is aborted, resources are not created", "Helm marks the release as FAILED. The hook's delete policy determines if the failed pod is cleaned up."),("hook-weight vs hook-delete-policy?",  "weight=execution order, delete-policy=cleanup timing", "Lower weight runs first. hook-delete-policy: hook-succeeded removes the pod after success; before-hook-creation removes before next run."),("How do chart tests differ from pods?", "Tests are annotated with helm.sh/hook: test", "Test pods run on demand with 'helm test'. They are not part of the normal release lifecycle and are deleted after running.")]),
    ("OCI Registries",      [("helm push vs helm repo push?",             "push=OCI registry, repo push=legacy HTTP chart museum", "Modern Helm uses OCI (helm push). Legacy chart repositories use HTTP and a chart museum server."),("List charts in OCI registry?",         "Use the registry's UI or: oras ls <registry>/<repo>", "OCI registries don't have a standard 'list' API. Use ORAS CLI or the registry's web interface."),("When to run helm dependency update?",  "After adding/changing dependencies in Chart.yaml", "It downloads charts to the charts/ directory and updates Chart.lock. Run before helm install/package if deps changed.")]),
    ("Production",          [("helm get values --all vs helm get values?","--all includes defaults+computed, without=user-supplied only", "Without --all you only see values explicitly set by the user. --all shows the complete merged values including chart defaults."),("Manage Helm secrets without values.yaml?","External Secrets Operator, Vault, or helm-secrets plugin", "helm-secrets encrypts values files with SOPS/GPG. ESO syncs secrets from Vault/AWS at runtime."),("What is helm-diff and why use it?",    "Shows a git-style diff of what upgrade would change", "Prevents surprises. Run before every production upgrade: helm diff upgrade myapp ./chart -f values.yaml")]),
],
"k8s": [
    ("kubeadm Bootstrap",   [("What if you don't disable swap?",          "kubelet refuses to start — hard requirement", "Kubernetes requires swap to be disabled for predictable memory management. kubelet checks on startup and fails if swap is on."),("What does CNI do and why not included?","CNI provides pod networking; K8s is CNI-agnostic by design", "Kubernetes defines the CNI interface but doesn't ship a plugin. You choose: Calico (policy), Cilium (eBPF), Flannel (simple)."),("Regenerate bootstrap token?",          "kubeadm token create --print-join-command", "Tokens expire after 24h by default. This creates a new one and prints the full join command.")]),
    ("RBAC",                [("Role vs ClusterRole?",                     "Role=namespace-scoped, ClusterRole=cluster-wide", "Roles grant permissions within one namespace. ClusterRoles apply across all namespaces or to cluster-level resources like Nodes."),("Check service account permissions?",   "kubectl auth can-i --list --as=system:serviceaccount:<ns>:<sa>", "The --as flag impersonates the service account. --list shows all permissions it has."),("What can the default service account do?","Very little — no RBAC permissions by default in modern K8s", "The default SA gets a token but no Role bindings. Best practice: create dedicated SAs for each workload.")]),
    ("Deployments",         [("readinessProbe vs livenessProbe?",        "readiness=ready for traffic, liveness=should it be restarted", "Failed readiness removes pod from Service endpoints — no traffic. Failed liveness kills and restarts the container."),("RollingUpdate with maxSurge=1 maxUnavailable=0?","One extra pod starts, old pod removed only after new is Ready", "Zero-downtime strategy: always have at least the requested replica count serving traffic during the update."),("Pause and resume a rollout?",          "kubectl rollout pause/resume deploy/<name>", "Pause stops new changes from being applied. Useful for canary testing — make some changes, pause, verify, then resume.")]),
    ("ConfigMaps & Storage",[("Enable encryption at rest for Secrets?",  "Configure EncryptionConfiguration in kube-apiserver", "Create an EncryptionConfig file with an AES or KMS provider and pass --encryption-provider-config to the API server."),("RWO vs ROX vs RWX access modes?",     "RWO=one node r/w, ROX=many nodes read, RWX=many nodes r/w", "Most cloud block storage is RWO. NFS supports RWX. ROX is rare. The PVC accessMode must match what the PV supports."),("WaitForFirstConsumer volumeBindingMode?","Delays PV provisioning until a Pod is scheduled", "Ensures the PV is provisioned in the same zone as the Pod. Without it, PV may be in wrong zone for Pod scheduling.")]),
    ("Ingress & NetworkPolicy",[("Ingress vs LoadBalancer Service?",      "Ingress=L7 HTTP routing, LoadBalancer=L4 with cloud IP", "One LoadBalancer per service = expensive. One Ingress controller + many Ingress rules = efficient."),("NetworkPolicies without CNI support?", "They are silently ignored — no enforcement", "NetworkPolicy enforcement requires a CNI that supports it: Calico, Cilium, or Weave. Flannel alone does NOT enforce policies."),("Allow traffic between two namespaces?", "NetworkPolicy with namespaceSelector matching both namespaces", "Use namespaceSelector: matchLabels: kubernetes.io/metadata.name: <ns> as an ingress from rule.")]),
    ("HPA",                 [("HPA scale on metrics besides CPU?",        "Memory, custom metrics (Prometheus), external metrics", "With metrics-server: CPU and memory. With Prometheus Adapter: any PromQL metric. With KEDA: event-driven sources."),("HPA vs VPA?",                          "HPA=scale out (replicas), VPA=scale up (resources)", "HPA adds/removes pods. VPA changes CPU/memory requests on existing pods. They can conflict — use carefully together."),("Test HPA scaling manually?",           "kubectl run load --image=busybox -- /bin/sh -c 'while true; do wget -q http://svc; done'", "Generate artificial load to trigger the HPA. Watch with: kubectl get hpa -w")]),
    ("Cluster Upgrades",    [("drain and DaemonSet pods?",               "DaemonSet pods are ignored (--ignore-daemonsets required)", "DaemonSets run on every node by design. drain skips them since they'll reschedule immediately on the same node."),("kubeadm upgrade apply vs upgrade node?","apply=control plane, node=worker nodes", "Run 'upgrade apply' once on the master. Run 'upgrade node' on each worker individually after draining it."),("Verify node upgraded successfully?",   "kubectl get nodes shows new version in VERSION column", "Also check: kubectl describe node <name> | grep kubelet. The kubelet version should match.")]),
    ("Troubleshooting",     [("Pod stuck in Pending — why?",              "No schedulable nodes: resource constraints, taints, affinity", "kubectl describe pod shows Events. Common reasons: insufficient CPU/memory, node taints, PVC not bound, image pull issue."),("Node shows NotReady — what does it mean?","kubelet stopped communicating with API server", "Check: journalctl -u kubelet on the node. Often: network issue, disk pressure, or kubelet crashed."),("Restore etcd snapshot?",               "Stop API server, run etcdctl snapshot restore, restart", "Full process: stop kube-apiserver, restore snapshot to new dir, update etcd manifest to point to new dir, restart.")]),
],
"compose": [
    ("First Stack",         [("How does Compose determine project name?","Directory name by default, or -p flag or COMPOSE_PROJECT_NAME", "The project name prefixes all resources: networks, volumes, container names. Change it with: docker compose -p myproject up."),("compose stop vs compose down?",        "stop=containers stopped, down=containers+networks removed", "stop preserves the containers (restart them later). down removes them. down -v also removes named volumes."),("Run one-off command in a service?",    "docker compose run --rm <service> <command>", "Starts a new container for the service (not the running one) and runs the command. --rm removes it after.")]),
    ("Build & Dev",         [("Order of env variable precedence?",       "shell env > .env file > compose.yaml environment > image ENV", "Shell environment always wins. Then .env file. Then compose.yaml environment:. Then Dockerfile ENV. Highest to lowest."),("How do anonymous volumes work?",       "Docker creates an unnamed volume, not accessible by name", "- /app/node_modules creates a volume that 'shadows' any bind mount at the parent. Keeps container's node_modules intact."),("Pass a .env file to Compose?",         "--env-file flag or place .env in project root (auto-loaded)", "docker compose --env-file .env.prod up. Compose auto-loads .env in the same dir as compose.yaml.")]),
    ("Networks",            [("Can a container be on multiple networks?","Yes — add it to multiple networks in the service definition", "Under networks: list multiple network names. The container gets a separate IP on each network."),("Give service a custom hostname?",      "hostname: key in the service definition", "The hostname is used for DNS within the network. Other services can reach it by both service name and hostname."),("network_mode: host?",                  "Container shares host network stack — no isolation", "No port mapping needed — container uses host ports directly. No network isolation. Useful for low-latency or monitoring tools.")]),
    ("Volumes",             [("Share a volume between services?",         "Reference the same named volume in both service volume: sections", "Both services must declare the same named volume name. The volume appears in the top-level volumes: section once."),("Named volumes on docker compose down?","Preserved — not deleted", "down only removes containers and networks. Use down -v to also remove named volumes. Intentional to protect data."),("Migrate data between volumes?",        "docker run with both volumes mounted, then copy files", "docker run --rm -v old:/from -v new:/to alpine cp -av /from/. /to/")]),
    ("Health Checks",       [("Four conditions in depends_on?",           "service_started, service_healthy, service_completed_successfully, service_failed", "service_started: container is running. service_healthy: healthcheck passes. service_completed_successfully: exited 0."),("What is start_period in healthcheck?", "Grace period before failed checks count", "During start_period, failing healthchecks don't mark service unhealthy. Useful for slow-starting apps."),("Check health status of a service?",    "docker compose ps shows health column; docker inspect shows Health.Status", "docker inspect --format='{{.State.Health.Status}}' <container> returns: healthy, unhealthy, starting.")]),
    ("Profiles",            [("Use different .env files per environment?","docker compose --env-file .env.prod up", "Combine with -f for full override: docker compose -f compose.yaml -f compose.prod.yaml --env-file .env.prod up -d"),("environment vs env_file in service?",  "environment=inline key-value, env_file=load from file", "environment: sets vars directly in compose.yaml. env_file: reads a file line by line and sets each as an env var."),("Prevent variable expansion in compose?","Use $$ instead of $ to escape", "$$VAR becomes the literal string $VAR in the container instead of being expanded by Compose.")]),
    ("Scaling",             [("Zero-downtime deploys with Compose?",      "Scale up new version alongside old, then scale down old", "docker compose up --scale api=2 with new image, verify health, then docker compose up --scale api=1 to remove old. Not ideal — use K8s for true zero-downtime."),("restart: always vs unless-stopped?",  "always=always restarts even after daemon restart; unless-stopped=not if manually stopped", "unless-stopped is better for production: if you manually stop a container (maintenance), it won't auto-restart on daemon restart."),("Docker secrets in Compose Swarm mode?","Use secrets: top-level key and reference in service", "Secrets are stored encrypted in Swarm. In the container they appear as files in /run/secrets/<name>.")]),
    ("Monitoring",          [("Restart one service without affecting others?","docker compose restart <service>", "Only that service's container is restarted. Other services continue running normally."),("Diff running config vs new config?",   "docker compose config shows merged config; compare with previous", "docker compose config outputs the fully-resolved configuration. Use diff against a saved previous version."),("Force-recreate one container?",        "docker compose up -d --force-recreate <service>", "Recreates the container even if the image and config haven't changed. Useful when environment changes aren't picked up.")]),
],
"actions": [
    ("First Workflow",      [("Difference: uses vs run in a step?",       "uses=run an Action (reusable unit), run=execute shell command", "uses: actions/checkout@v4 runs the checkout Action. run: npm test runs a shell command directly on the runner."),("Events that trigger workflows?",       "push, pull_request, schedule, workflow_dispatch, release, and 25+ more", "See full list at docs.github.com/actions/writing-workflows/events. workflow_dispatch adds a manual trigger button in the UI."),("Manually trigger from GitHub UI?",     "Add 'on: workflow_dispatch:' then click 'Run workflow' in Actions tab", "workflow_dispatch can accept inputs (string, boolean, choice) that appear as form fields in the UI.")]),
    ("CI Pipeline",         [("What does matrix strategy do here?",       "Creates 2 parallel jobs — one per node version", "matrix: node-version: ['20','22'] creates 2 jobs. 3 versions = 3 jobs. N×M combinations multiply jobs."),("upload-artifact vs cache?",            "artifact=store files between jobs/runs, cache=speed up installs", "Artifacts persist after the run for download. Cache is for dependencies that shouldn't change often (node_modules, pip)."),("Skip CI for a commit?",               "Add [skip ci] or [ci skip] to commit message", "GitHub recognizes these strings and skips workflow runs. Also works: skip-checks: true in PR description.")]),
    ("Docker Build & Push", [("What does cache-from: type=gha do?",       "Uses GitHub Actions cache for Docker layer cache", "BuildKit stores layer cache in GitHub's cache service. Dramatically speeds up builds when layers haven't changed."),("Why 'packages: write' permission?",   "To push images to GitHub Container Registry (ghcr.io)", "GHCR is under the packages API. Without write permission, the push will fail with 403."),("Build multi-platform images?",         "docker/setup-qemu-action + platforms: linux/amd64,linux/arm64", "QEMU emulates ARM on x86 runners. Add setup-qemu-action before setup-buildx-action, then add platforms: to build-push-action.")]),
    ("Secrets",             [("Repo secrets vs environment secrets?",     "Environment secrets only available when targeting that environment", "Repo secrets are always available. Environment secrets require the job to reference that environment — enabling approval gates."),("Prevent secret in logs?",              "GitHub masks values automatically; never echo secrets", "GitHub redacts known secret values from logs. But avoid concatenating secrets with other strings which can break masking."),("What is OIDC and why better?",         "Federated identity token — no long-lived credentials stored", "OIDC lets cloud providers verify GitHub's identity. No API keys to rotate or leak. AWS/GCP/Azure all support it.")]),
    ("Reusable Workflows",  [("Reusable workflow vs composite action?",   "Reusable=separate job, Composite=steps in calling job", "Reusable workflows have their own job (separate runner, secrets, permissions). Composite actions run as steps inline."),("Pass outputs from reusable workflow?", "Declare outputs: in the called workflow, reference via needs.job.outputs.key", "The called workflow defines outputs: at the workflow level. The caller accesses them via needs.<job-id>.outputs.<name>."),("Reusable workflow call another?",      "Yes — up to 4 levels of nesting", "GitHub supports chaining reusable workflows up to 4 levels deep. Circular calls are not allowed.")]),
    ("Full CI/CD Pipeline", [("What does 'needs' do?",                   "Creates dependency between jobs — waits for listed jobs to complete", "needs: [test, build] means this job only starts when both test and build succeed. Jobs without 'needs' run in parallel."),("Pass data between jobs?",              "Use outputs: on the producing job, reference via needs.<job>.outputs.<key>", "Steps set outputs with: echo 'key=value' >> $GITHUB_OUTPUT. Jobs expose them under outputs: in the job definition."),("Add manual approval for production?",  "Create a 'production' environment with required reviewers", "In Settings > Environments > production, add required reviewers. The workflow pauses until someone approves.")]),
    ("Caching",             [("Cache eviction policy?",                  "LRU eviction after 7 days of no access, 10GB per repo limit", "Caches not accessed in 7 days are evicted. Total cache storage per repo is 10GB. Oldest caches are evicted first."),("Force-invalidate a cache?",            "Change the cache key (e.g. add a suffix) or delete via GitHub UI/API", "Actions > Caches in GitHub UI lets you delete specific caches. Or change the key: prefix in the workflow."),("Maximum cache size per repo?",         "10 GB total across all branches and caches", "When the limit is reached, GitHub evicts older caches. Plan cache keys to avoid hitting this limit.")]),
    ("Security 2026",       [("GITHUB_TOKEN vs PAT?",                    "GITHUB_TOKEN=auto-generated per run, PAT=manually created long-lived token", "GITHUB_TOKEN expires when the run ends and has limited scope. PATs are dangerous — they don't expire by default and have broad access."),("Prevent secret exfiltration via compromised action?","Pin actions to SHA, use egress firewall, minimal permissions", "A compromised action running with write:all can exfiltrate secrets. SHA pinning ensures you run the exact code you audited."),("What is pull_request_target and why dangerous?","Runs in context of BASE branch with write permissions", "Unlike pull_request, it can access secrets. A malicious PR can exploit this to exfiltrate secrets if not carefully guarded.")]),
],
"argocd": [
    ("Install ArgoCD v3",   [("--server-side --force-conflicts on install?","Applies manifests server-side to handle CRD size limits", "ArgoCD CRDs exceed kubectl's client-side limit. Server-side apply handles them without the 'too long' error."),("argocd-server vs argocd-repo-server?","server=API/UI, repo-server=git clone and template rendering", "repo-server handles the expensive work: cloning repos, rendering Helm/Kustomize. Scaling it improves performance."),("Expose ArgoCD with LoadBalancer?",     "Set service.type: LoadBalancer in ArgoCD values or patch the service", "kubectl patch svc argocd-server -n argocd -p '{\"spec\":{\"type\":\"LoadBalancer\"}}'. Add TLS termination at the LB.")]),
    ("First Application",   [("OutOfSync vs Degraded?",                  "OutOfSync=cluster differs from Git, Degraded=resources unhealthy", "OutOfSync means the desired state (Git) doesn't match actual state. Degraded means resources exist but aren't healthy."),("prune: true effect?",                  "Resources deleted from Git are also deleted from cluster", "Without prune, removed manifests leave orphaned resources in the cluster. prune keeps Git as the single source of truth."),("selfHeal and when to disable?",        "selfHeal reverts manual cluster changes to match Git", "Disable selfHeal temporarily during debugging or emergency hotfixes. Re-enable after committing changes to Git.")]),
    ("Helm with ArgoCD",    [("Override Helm values in ArgoCD?",          "Use helm.values inline YAML or helm.valueFiles referencing Git files", "valueFiles: [$values/envs/prod.yaml] references a file in the repo. values: | sets inline YAML overrides."),("Force specific Helm chart version?",   "Set targetRevision: '1.2.0' in the source spec", "Pin exact version for production. Use '~1.2' for patch-only updates. Avoid 'latest' or '*' in production."),("What is 'ref' in multiple sources?",   "A reference name to use the repo's files in another source's valueFiles", "ref: values creates an alias. Other sources use $values/path to reference files from that repo.")]),
    ("Projects & RBAC",     [("clusterResourceWhitelist vs namespaceResourceBlacklist?","whitelist=allow these cluster resources, blacklist=deny these namespace resources", "Whitelist controls what cluster-scoped resources (Nodes, PVs) the project can create. Blacklist prevents specific namespace resources."),("Add GitHub team SSO to ArgoCD RBAC?", "Configure Dex with GitHub connector, map teams to ArgoCD groups", "In argocd-cm: set dex.config with GitHub OAuth. In argocd-rbac-cm: map 'org:team' to ArgoCD roles."),("App deploys outside Project's destinations?","ArgoCD rejects the sync with a permission error", "ArgoCD enforces destination restrictions at sync time. The Application will show an error and won't sync.")]),
    ("Sync Policies",       [("Four conditions in depends_on?",           "service_started, service_healthy, service_completed_successfully, service_failed", "In sync context: ArgoCD doesn't use depends_on directly, but sync waves control ordering with health checks between waves."),("Force manual sync when automated?",   "argocd app sync <name> or click Sync in the UI", "Automated sync still allows manual triggers. Use --force to replace diverged resources or --prune to clean up extras."),("allowEmpty: false protects against?",  "Accidental deletion of all resources if the source returns empty", "If a bug causes the template to render nothing, allowEmpty: false prevents ArgoCD from deleting everything.")]),
    ("ApplicationSets",     [("Other generators besides clusters?",       "git, list, matrix, merge, SCM provider, pull request, cluster decision resource", "git generator creates apps per directory or per file. list generator uses hardcoded values. matrix combines two generators."),("Register external cluster with ArgoCD?","argocd cluster add <context-name>", "ArgoCD uses the kubeconfig context to connect. It creates a ServiceAccount and ClusterRoleBinding on the target cluster."),("App when cluster label no longer matches?","ApplicationSet controller deletes the Application", "This is the automatic lifecycle management of ApplicationSets. The Application and its resources are pruned.")]),
    ("Notifications",       [("Notify on success vs failure?",            "Use different triggers: on-sync-succeeded vs on-sync-failed", "ArgoCD notifications has built-in triggers. Subscribe with: notifications.argoproj.io/subscribe.<trigger>.<service>=<channel>"),("Metrics removed in ArgoCD v3?",        "argocd_app_sync_status, argocd_app_health_status, argocd_app_created_time", "Use argocd_app_info with labels instead. It carries the same data as label dimensions: health_status, sync_status."),("Webhook notifications for GitHub?",    "Configure GitHub webhook pointing to ArgoCD notifications webhook service", "ArgoCD can receive webhooks from GitHub to trigger immediate syncs instead of waiting for polling interval.")]),
    ("Production",          [("Standard vs HA install difference?",       "HA has multiple replicas of each component + Redis Sentinel", "Standard = single replica of everything. HA = 2-3 replicas of server/repo-server + Redis HA. Requires 3+ nodes for anti-affinity."),("Backup and restore ArgoCD state?",    "argocd admin export > backup.yaml / argocd admin import < backup.yaml", "Exports all Applications, Projects, repos, cluster secrets. Store in Git. Restore after a cluster rebuild."),("App of Apps pattern?",                 "One ArgoCD Application that manages other ArgoCD Applications", "The root app points to a Git directory of Application manifests. ArgoCD manages itself. Enables full GitOps for the platform itself.")]),
],
"prom": [
    ("kube-prometheus-stack",[("Components in kube-prometheus-stack?",   "Prometheus Operator, Prometheus, Alertmanager, Grafana, kube-state-metrics, Node Exporter", "One Helm chart deploys the entire monitoring stack. Each component is separately configurable via Helm values."),("What does Prometheus Operator do?",   "Manages Prometheus instances via Kubernetes CRDs", "The Operator watches for PrometheusRule, ServiceMonitor, PodMonitor CRDs and reconfigures Prometheus automatically. No manual config reload needed."),("Check running Prometheus config?",     "kubectl exec -n monitoring prometheus-pod -- cat /etc/prometheus/config_out/prometheus.env.yaml", "Or access the UI at /config endpoint. The Operator generates config from your CRDs into this file.")]),
    ("PromQL",              [("rate() vs irate()?",                       "rate=average over window, irate=instant rate from last 2 samples", "rate() is smoother and better for alerting. irate() is more responsive but spiky. Use rate() for dashboards and alerts."),("Never use counter without rate()?",   "Counters only ever increase — raw value is meaningless", "A counter showing 1,000,000 tells you nothing. rate(counter[5m]) tells you how fast it's increasing right now."),("{status=~'5..'} matcher?",             "Regex match: selects labels where status starts with 5 (500, 502, 503...)", "=~ uses RE2 regex. 5.. matches 5 followed by any 2 characters. Use !~ for negative regex match.")]),
    ("ServiceMonitors",     [("ServiceMonitor vs PodMonitor?",            "ServiceMonitor scrapes via Service, PodMonitor scrapes Pod IPs directly", "Use ServiceMonitor when pods have a Service. Use PodMonitor for pods without a Service (e.g. DaemonSets)."),("Scrape non-Kubernetes target?",        "Use a static scrape config or ScrapeConfig CRD with static_configs", "Add a ScrapeConfig CR with static_configs pointing to the external host:port. The Operator merges it into prometheus.yaml."),("What does 'release: prometheus' label do?","Matches the ServiceMonitor to the Prometheus instance's selector", "The Prometheus CR has serviceMonitorSelector. Only ServiceMonitors with matching labels are picked up. Without it, your monitor is ignored.")]),
    ("Alerting",            [("'for' duration vs 'group_wait'?",          "for=condition must be true this long before alert fires; group_wait=delay before first notification", "for: 5m prevents flapping — transient spikes don't alert. group_wait: 30s batches multiple firing alerts into one notification."),("What does a recording rule do?",       "Pre-computes an expensive PromQL expression and stores it as a new metric", "Querying a recording rule is instant — the heavy computation already ran. Use for frequently-queried aggregations."),("Silence an alert in Alertmanager?",   "Create a silence in Alertmanager UI or via API matching the alert's labels", "Silences are time-bounded. Set end time carefully. They don't stop the alert from firing — only suppress notifications.")]),
    ("Exporters",           [("MemFree vs MemAvailable?",                 "MemFree=completely unused RAM, MemAvailable=RAM available for new apps", "MemAvailable includes reclaimable cache/buffers. It's the realistic 'free' memory. MemFree is the kernel's exact free pages."),("Add custom Node Exporter text collector?","Drop a .prom file into Node Exporter's --collector.textfile.directory", "Any process can write Prometheus format metrics to a .prom file. Node Exporter reads and exposes them. Great for custom scripts."),("Monitor StatefulSet replica count?",   "kube_statefulset_replicas vs kube_statefulset_status_replicas_ready", "kube-state-metrics exports these. Alert when ready < desired for more than N minutes.")]),
    ("Thanos",              [("Minimum retention when using Thanos?",     "2h — enough for Thanos sidecar to upload blocks", "Prometheus blocks are created every 2 hours. Thanos uploads them to object storage. After upload, Prometheus doesn't need them."),("Thanos handle HA Prometheus duplicates?","Thanos Querier deduplicates using the replica label", "Tag each Prometheus with a unique replica label. Querier identifies and deduplicates series with the same labels except replica."),("Querier vs Query Frontend?",           "Querier fetches data, Query Frontend caches/shards expensive queries", "Query Frontend sits in front of multiple Queriers. It caches results and splits large time-range queries into parallel sub-queries.")]),
    ("SLOs",                [("What is an error budget?",                 "Allowed amount of downtime/errors to maintain the SLO", "99.9% availability SLO = 0.1% error budget = 43.2 min/month. Burning it fast triggers alerts. Unused budget allows risk-taking."),("Burn rate of 1 means?",               "Consuming error budget at exactly the rate that exhausts it in the SLO window", "Burn rate 1 over 30 days = budget gone in 30 days. Burn rate 14.4 = budget gone in ~2 days. Alert at high burn rates."),("Google multi-window burn rate thresholds?","Critical: 14.4x for 1h+5m; Warning: 6x for 6h+30m", "From the Google SRE Workbook. Multi-window reduces false positives: both windows must exceed threshold simultaneously.")]),
    ("Production",          [("What is cardinality?",                     "Number of unique time series = unique label value combinations", "metric{a='x', b='y'} and metric{a='x', b='z'} are 2 series. 100 unique users as labels = 100 series. Scales exponentially."),("Drop labels from a scraped metric?",   "Use metric_relabel_configs with action: labeldrop", "In ServiceMonitor or scrape config: metricRelabelings: - action: labeldrop, regex: (unwanted_label)"),("Find targets producing most series?",  "Prometheus UI: Status > TSDB Status shows top metrics by series count", "Also: topk(10, count by (__name__)({__name__=~'.+'})) in PromQL — expensive query, run sparingly.")]),
],
"grafana": [
    ("Data Sources",        [("Pre-provision dashboards on startup?",     "Use provisioning ConfigMaps with dashboards in /var/lib/grafana/dashboards/", "Create a Grafana dashboard provider config pointing to a directory. Mount dashboard JSON files via ConfigMap. They appear automatically."),("Grafana OSS vs Enterprise vs Cloud?", "OSS=free open source, Enterprise=paid RBAC/SSO/plugins, Cloud=hosted SaaS", "OSS has all core features. Enterprise adds LDAP sync, data source permissions, reporting. Cloud is fully managed with generous free tier."),("Reset admin password?",               "grafana-cli admin reset-admin-password <new-password>", "Run inside the Grafana pod: kubectl exec -n monitoring <pod> -- grafana-cli admin reset-admin-password newpass")]),
    ("Dashboards",          [("What is a template variable?",             "A dynamic dropdown that filters panel queries", "Variables are defined in Dashboard Settings. Panels reference them as $variable or ${variable}. They filter all panels simultaneously."),("Link panels with data links?",         "Add Data Links in panel settings with URL and query parameters", "Data links can open Explore with pre-filled queries, jump to other dashboards, or open external URLs using panel field values."),("Version control Grafana dashboards?",  "Export as JSON, store in Git, provision via ConfigMap", "Grafana UI > Dashboard > Share > Export JSON. Store in Git. Use Grafonnet for code-generated dashboards.")]),
    ("Unified Alerting",    [("Grafana Unified vs Alertmanager?",         "Grafana Unified=multi-datasource alerts in Grafana, Alertmanager=Prometheus-only routing", "Grafana Unified Alerting can alert on Loki, Prometheus, and any data source. Alertmanager only receives alerts from Prometheus."),("Mute alert during maintenance?",       "Create a Silence in Alerting > Silences with a time window", "Silences match alert labels. They suppress notifications but don't stop evaluation. Set expiry to match maintenance window."),("Test alert rule without waiting?",     "Use 'Test rule' button in Alert Rule editor or set a short 'For' duration temporarily", "The Test button evaluates the query immediately and shows if the condition is currently met, without creating a real alert.")]),
    ("Grafana Alloy",       [("Alloy vs Promtail?",                       "Alloy=unified agent (metrics+logs+traces), Promtail=logs only", "Promtail is log-only and being deprecated. Alloy replaces Promtail, Grafana Agent, and can replace OTel Collector in many cases."),("How do Alloy components communicate?", "Via typed references — outputs connect to receivers", "forward_to = [loki.write.default.receiver] passes log entries from one component to another. It's a pipeline graph."),("Debug an Alloy config?",               "alloy run --stability.level=experimental config.river, check /metrics and /-/ready endpoints", "Alloy exposes its own metrics on port 12345. Use the built-in UI at /graph to visualize the component pipeline.")]),
    ("Dashboards as Code",  [("Alternatives to Grafonnet?",               "Grizzly (grr), Terraform Grafana provider, grafana-dashboard-manager", "Grizzly uses YAML/Jsonnet. Terraform provider manages dashboards as infrastructure. All solve the 'dashboards in Git' problem."),("Import dashboard via Grafana API?",    "POST /api/dashboards/db with dashboard JSON", "curl -X POST http://admin:pass@host:3000/api/dashboards/db -H 'Content-Type: application/json' -d @dashboard.json"),("Prevent UI changes overwriting provisioned dashboards?","Set allowUiUpdates: false in dashboard provider config", "With allowUiUpdates: false, the dashboard is read-only in the UI. Changes must be made in the JSON file and reloaded.")]),
    ("Correlation",         [("Configure Exemplars to link metrics to traces?","Enable exemplars in Prometheus and set trace ID label in Grafana data source", "Prometheus scrapes exemplars from apps. In Grafana Prometheus data source, set traceLogsCorrelation with the Tempo data source UID."),("Labels that must match for correlation?","service_name or app label must match between Prometheus and Loki streams", "Grafana uses a label mapping to jump from metric series to log stream. The mapping must use a common label value."),("Set up trace context propagation?",   "Inject W3C TraceContext headers (traceparent) in HTTP requests between services", "Use OTel SDK with propagators: [tracecontext]. Each service reads/writes the traceparent header to maintain the trace ID chain.")]),
    ("OnCall",              [("Grafana OnCall vs PagerDuty?",              "OnCall=open source self-hosted, PagerDuty=paid SaaS", "OnCall has rotations, escalations, Slack/Teams integration. PagerDuty adds analytics, mobile app, and SLA guarantees. OnCall is free for self-hosters."),("Set up follow-the-sun rotation?",     "Create overlapping schedules per timezone, each covering their business hours", "Add schedule 1: EU team Mon-Fri 9-17 CET. Schedule 2: US team Mon-Fri 9-17 EST. They hand off automatically."),("Acknowledge alert from Slack?",        "Click 'Acknowledge' button in the OnCall Slack notification message", "OnCall sends rich Slack messages with action buttons. Acknowledging assigns the alert to you and stops escalation.")]),
    ("Production",          [("Migrate Grafana SQLite to PostgreSQL?",    "Export all content, set GF_DATABASE_TYPE=postgres, reimport", "Use grafana-cli or Grizzly to export dashboards/datasources. Update env vars. On first start with Postgres, reimport everything."),("Grafana Mimir vs Prometheus?",         "Mimir=horizontally scalable Prometheus-compatible backend for massive scale", "Mimir uses object storage (S3) and can handle 10x the metrics of a single Prometheus. Use it when you outgrow Prometheus."),("SAML SSO for Grafana Enterprise?",    "Set GF_AUTH_SAML_ENABLED=true and configure IdP metadata URL in Grafana config", "Grafana Enterprise supports SAML 2.0 with Okta, Azure AD, Auth0. OSS supports OAuth (GitHub, Google, Generic OAuth).")]),
],
"loki": [
    ("Deploy Loki",         [("Loki monolithic vs simple-scalable vs microservices?","monolithic=1 pod, simple-scalable=read/write split, microservices=each component separate", "For dev: monolithic (loki.deploymentMode: SingleBinary). For prod: simple-scalable or microservices for independent scaling."),("How Alloy determines which pods to collect logs from?","Kubernetes service discovery — all pods by default, filtered by relabeling", "discovery.kubernetes role=pod discovers all pods. Add relabeling rules to include/exclude by namespace or labels."),("Verify Loki is receiving logs?",       "In Grafana Explore: select Loki, query {} to see all streams", "Or: curl http://loki-gateway/loki/api/v1/labels to see label names. An empty response means no logs yet.")]),
    ("LogQL",               [("Difference |= vs |~?",                     "|= is exact string match, |~ is regex match", "|= 'error' finds lines containing exactly 'error'. |~ 'err|Error|ERR' finds any of those patterns using regex."),("What does 'unwrap' do?",              "Extracts a numeric value from a log field for metric queries", "unwrap duration converts a log field (e.g. duration=1.2s) to a numeric value usable in quantile_over_time, avg_over_time, etc."),("Search across multiple namespaces?",   "{namespace=~'ns1|ns2'} or use multiple stream selectors", "Regex in label selectors: {namespace=~'prod|staging'} selects both namespaces in one query.")]),
    ("Labels",              [("Recommended max active streams?",          "Under 10,000 per Loki instance for healthy performance", "Monitor loki_ingester_streams_created_total. Too many streams = high memory + slow queries. Reduce cardinality in labels."),("Add K8s metadata as labels automatically?","Grafana Alloy or Promtail with kubernetes_sd_config does this automatically", "Alloy's loki.source.kubernetes component automatically extracts namespace, pod, container as labels from the K8s API."),("Label vs structured metadata in Loki v3?","Labels=indexed for stream selection, metadata=stored but not indexed", "Structured metadata (OTel attributes) is searchable at query time but doesn't create new streams. Best of both worlds.")]),
    ("OTel Collector",      [("OTel Collector vs Grafana Alloy?",         "Collector=vendor-neutral CNCF standard, Alloy=Grafana-specific with River config", "Alloy supports OTel natively and adds Grafana-specific features. Collector is more portable. Both work well with Loki/Tempo."),("Add sampling to reduce trace volume?", "Use tailsampling or probabilistic_sampler processor in the Collector", "probabilistic_sampler: sampling_percentage: 10 keeps 10% of traces. tail_sampling keeps 100% of error traces."),("What does resourcedetection processor do?","Automatically detects and adds resource attributes (K8s node, cloud provider...)", "Adds metadata like k8s.node.name, cloud.region automatically. Enriches telemetry without changing application code.")]),
    ("Instrumentation",     [("OTel auto-instrumentation languages?",     "Node.js, Python, Java, .NET, Go, PHP, Ruby", "The OTel Operator injects language-specific SDKs as init containers. Just add the annotation to your Deployment."),("Head-based vs tail-based sampling?",   "Head=decision at trace start (fast), Tail=decision after all spans received (accurate)", "Head sampling is simple and low-overhead. Tail sampling can keep 100% of error traces and sample the rest — requires buffering."),("Add custom attributes to a trace?",   "Use the OTel SDK span API: span.setAttribute('key', value)", "const span = tracer.startSpan('operation'); span.setAttribute('user.id', userId); span.end();")]),
    ("Tracing with Tempo",  [("What is an Exemplar?",                     "A data point in a metric that carries a trace ID linking it to a specific trace", "When a request takes 2 seconds (the metric), the exemplar records the trace ID of that exact request. Click it in Grafana to jump to the trace."),("Tempo vs Jaeger?",                    "Tempo=cost-efficient object storage backend, Jaeger=more UI features", "Tempo stores in S3/GCS cheaply and uses TraceQL. Jaeger has richer UI and dependency graphs. Both accept OTel traces."),("Configure tail-based sampling in Tempo?","Use Tempo's built-in tail_sampling config in the distributor", "Tempo supports tail sampling natively — keep 100% of error traces, sample happy-path traces at a lower rate.")]),
    ("Log Alerting",        [("Test a Loki ruler alert?",                 "logcli rules eval or create a test alert with a short 'for' duration", "logcli is the Loki CLI. Or set for: 10s temporarily and check Alertmanager receives it. Reset to production value after."),("Loki alerting vs Grafana Unified Alerting on Loki?","Ruler=in Loki itself, Grafana Unified=in Grafana, evaluated by Grafana", "Loki Ruler evaluates rules continuously in the Loki process. Grafana Unified Alerting polls Loki on a schedule. Ruler is more efficient for high-volume log alerting."),("Recording rules in Loki?",            "Define metric_query rules in the ruler config — same format as alert rules", "Recording rules pre-compute expensive LogQL metric queries and store results as Prometheus-compatible metrics.")]),
    ("Production",          [("Implement tail-based sampling for error traces?","Use tail_sampling processor: policy keep errors 100%, sample rest at 10%", "tail_sampling: policies: - name: errors, type: status_code, status_code: {status_codes: [ERROR]}. Add a probabilistic policy for the rest."),("Max cardinality for Loki labels?",    "Under 10,000 unique label value combinations per tenant", "Each unique combination creates a new stream. Beyond 10k streams per ingester, query performance degrades and memory spikes."),("Migrate Promtail to Alloy?",          "Replace Promtail config with equivalent Alloy River config using loki.source.kubernetes", "Alloy's loki.source.kubernetes replaces Promtail's kubernetes_sd_configs. Pipeline stages map to loki.process stages.")]),
],
}

def wrap(c, text, font, size, max_w):
    words = text.split(); cur = ""; lines = []
    for w in words:
        test = (cur + " " + w).strip()
        if stringWidth(test, font, size) <= max_w: cur = test
        else:
            if cur: lines.append(cur)
            cur = w
    if cur: lines.append(cur)
    return lines

def draw_guide_image(c, t, guide_qa):
    """Draw a single 1080x1080 answer key image for one guide."""
    # Background
    c.setFillColor(HexColor("#F8FAFC")); c.rect(0,0,W,H,fill=1,stroke=0)
    # Top header bar
    c.setFillColor(t['d']); c.rect(0,H-90,W,90,fill=1,stroke=0)
    c.setFillColor(t['p']); c.rect(0,H-96,W,6,fill=1,stroke=0)
    # Header text
    c.setFillColor(WHITE); c.setFont("Helvetica-Bold",11)
    c.drawString(30,H-34,"ESSENTIAL TRAINING SERIES  ·  ANSWER KEY")
    c.setFont("Helvetica-Bold",42); c.drawString(30,H-80,t['name'])
    c.setFont("Helvetica-Bold",13)
    c.drawRightString(W-30,H-42,t['version'])
    c.drawRightString(W-30,H-70,"Answer Key — All Exercises")

    # Layout: 2 columns of exercises
    PAD = 28; COL_W = (W - PAD*3) // 2; ROW_H = 112; COLS = 2
    exercises = guide_qa
    n = len(exercises)
    rows = (n + 1) // 2
    start_y = H - 110

    for idx, (ex_title, qas) in enumerate(exercises):
        col = idx % COLS
        row = idx // COLS
        x = PAD + col * (COL_W + PAD)
        y = start_y - row * ROW_H - ROW_H

        # Exercise card bg
        c.setFillColor(WHITE)
        c.roundRect(x, y, COL_W, ROW_H - 6, 8, fill=1, stroke=0)
        c.setStrokeColor(t['m']); c.setLineWidth(1.2)
        c.roundRect(x, y, COL_W, ROW_H - 6, 8, fill=0, stroke=1)
        # Top stripe
        c.setFillColor(t['p'])
        c.roundRect(x, y + ROW_H - 6 - 28, COL_W, 28, 8, fill=1, stroke=0)
        c.rect(x, y + ROW_H - 6 - 14, COL_W, 14, fill=1, stroke=0)
        # Exercise number pill
        c.setFillColor(t['d'])
        c.roundRect(x+8, y + ROW_H - 6 - 24, 26, 18, 4, fill=1, stroke=0)
        c.setFillColor(WHITE); c.setFont("Helvetica-Bold",9)
        c.drawCentredString(x+21, y + ROW_H - 6 - 18, f"{idx+1:02d}")
        # Exercise title
        c.setFillColor(WHITE); c.setFont("Helvetica-Bold",11)
        title_w = COL_W - 52
        title_lines = wrap(c, ex_title, "Helvetica-Bold", 11, title_w)
        c.drawString(x+42, y + ROW_H - 6 - 18, title_lines[0] if title_lines else ex_title)

        # Q&A items
        inner_y = y + ROW_H - 40
        for qi, (q_text, ans, expl) in enumerate(qas[:3]):
            inner_y -= 4
            # Tiny Q bullet
            c.setFillColor(t['m']); c.circle(x+14, inner_y+3, 4, fill=1, stroke=0)
            c.setFillColor(WHITE); c.setFont("Helvetica-Bold",5.5)
            c.drawCentredString(x+14, inner_y+1, "Q")
            # Question (truncated)
            q_short = q_text if len(q_text) <= 48 else q_text[:46]+"…"
            c.setFillColor(HexColor("#374151")); c.setFont("Helvetica-Bold",8.5)
            c.drawString(x+24, inner_y+1, q_short)
            inner_y -= 14
            # Answer
            c.setFillColor(HexColor("#15803D")); c.setFont("Helvetica-Bold",8.5)
            ans_short = ans if len(ans) <= 62 else ans[:60]+"…"
            c.drawString(x+24, inner_y+1, "→ "+ans_short)
            inner_y -= 13
            # Explanation
            c.setFillColor(GRAY); c.setFont("Helvetica-Oblique",7.5)
            ex_short = expl if len(expl) <= 75 else expl[:73]+"…"
            c.drawString(x+24, inner_y+1, ex_short)
            inner_y -= 4

    # Bottom bar
    c.setFillColor(t['d']); c.rect(0,0,W,44,fill=1,stroke=0)
    c.setFillColor(t['p']); c.rect(0,44,W,4,fill=1,stroke=0)
    c.setFillColor(WHITE); c.setFont("Helvetica-Bold",12)
    c.drawString(30,16,f"{t['name']} Essential Training — Answer Key  ·  {t['version']}")
    c.setFont("Helvetica",10)
    c.drawRightString(W-30,16,"#DevOps  #Kubernetes  #CloudNative")

# Build all 10 images
guide_order = ["k3s","docker","helm","k8s","compose","actions","argocd","prom","grafana","loki"]
file_names  = ["K3s","Docker","Helm","Kubernetes","DockerCompose","GitHubActions","ArgoCD","Prometheus","Grafana","Loki_OpenTelemetry"]

for key, fname in zip(guide_order, file_names):
    t = GUIDES[key]
    qa = QA_DATA[key]
    out = f"{OUT}/{fname}_AnswerKey.pdf"
    c = canvas.Canvas(out, pagesize=(W,H))
    draw_guide_image(c, t, qa)
    c.showPage(); c.save()
    print(f"✓ {out}")

print("\n✅ All 10 answer key images generated!")
